### ISSUE TITLE
TVD Arbori path seems not working, autosave conflict with oracle vscode tools plugin?

### ISSUE THREAD

**Issue by yevon** [sd1337/sqlcl-codescan-extension#1]
I have a problem trying to make the formatter to work with the same arbori configuration file as I have on sqldeveolper. I tried setting it with this path, but it doesn't seem to work:

".vscode\codestyle.arbori"

![image](https://github.com/sd1337/sqlcl-codescan-extension/assets/121157/5457f800-17c3-4870-9b72-0ba24a1871e0)

It just says "Formatting file ... using default formatter".

 Also I've set it as default formatter, but when I do have Oracle tools installed it seems that it's formatter takes precedence even when I set sqlcl-codescan-extension as default. Any ideas? The extension doesn't trigger the formatter on save, maybe I have a setup issue. Right now it only works for me when calling it explicitly with Format with... and selecting this extension. Thanks!

**Comment by sd1337** [comment]
I think you miss the configuration for Tvd Formatter Path as it is required to actually load the arbori style formatter. Thats something thats I will make more clear in the readme and also show a warning in the output if its missing. it should look like this:
![image](https://github.com/sd1337/sqlcl-codescan-extension/assets/10446389/cd0b8598-f415-445b-9d45-2147ae99c205)
Concerning oracle tools formatter, you should be able to change the formatter for Oracle SQL file with the command "Format Document With"
![image](https://github.com/sd1337/sqlcl-codescan-extension/assets/10446389/1620e181-b731-4a5f-885c-1da6ec3b1c3b)
and the "Configure Default Formatter"
![image](https://github.com/sd1337/sqlcl-codescan-extension/assets/10446389/198758ac-0f88-49bf-b31d-3b8af4449c2d)
If you want to have the formatting run on save theres a general VS Code option that allows that, just open you preferences and search for "format on save"
![image](https://github.com/sd1337/sqlcl-codescan-extension/assets/10446389/29cedb9f-a85d-48e8-8cfc-1e22078079a6)

**Comment by yevon** [comment]
Thanks! I will give it a try. Oracle yesterday released a new much more complete official extension for vscode called  SQL Developer, I'll check it also as it maybe implements a proper sqlcl code formatter.

**Comment by sd1337** [comment]
Yeah, if already installed den sql dev extension and look how i can integrate it but I also assume that sooner or later oracle itself will implement what i've done here

**Comment by yevon** [comment]
Sorry I don't quite control this stuff about formatting of the tvd formatter , just the arbori rules, where I can find the format.js file of the tvd formatter, is it a library or standard or is user defined? As you said, if I put a file in the tvd formatter the log shows that is using a custom formatter now :).

**Comment by sd1337** [comment]
This is the Trivadis Report with all files
https://github.com/Trivadis/plsql-formatter-settings
The format.js file is found here:
https://github.com/Trivadis/plsql-formatter-settings/tree/main/sqlcl
